# Generated by Django 2.1.5 on 2019-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_genres',
            field=models.ManyToManyField(related_name='genres', to='philm.Genres', verbose_name='Genres'),
        ),
    ]
