# Generated by Django 2.1.5 on 2019-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philm', '0002_auto_20190323_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_genres',
            field=models.ManyToManyField(to='philm.Genres', verbose_name='Genres'),
        ),
    ]
