# Generated by Django 2.1.5 on 2019-03-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philm', '0003_auto_20190323_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviews_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
