# Generated by Django 2.1.5 on 2019-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philm', '0005_auto_20190328_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviews_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
