# Generated by Django 2.1.5 on 2019-03-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philm', '0006_reviews_reviews_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_updated',
        ),
    ]
